### PR TITLE
BAU: fix Codacy coverage reporting

### PR DESCRIPTION
**Pull request by bjgill**
Following the Codacy suggestions, I've got it working.

### CODE REVIEW

**Comment by bjgill** [comment]
(I'm just going to wait until Codacy has finished before asking for reviews)

**Comment by bjgill** [comment]
OK - it's successfully reporting to Codacy. See https://app.codacy.com/app/alphagov/verify-hub/pullRequest?prid=3655065

However, Codacy doesn't like the coverage. Maybe this is because there is no coverage data on master? I propose merging this so that we start getting coverage data, and then keeping an eye on future PRs...

**Comment by CharlesIC** [comment]
Well spotted! I tried to fix it a while ago but didn't get round to figuring out why it was failing in Travis.

**Comment by bjgill** [comment]
Added github authentication so we don't fall foul of the API rate limiting

**Comment by CharlesIC** [comment]
Where did you get `$GITHUB_PAT` from?

**Comment by bjgill** [comment]
It's the new secure variable

**Comment by CharlesIC** [comment]
Yes - but how did you generate the token? For which GitHub user did you generate it? For the `ida-codacy-bot` accont?

**Comment by bjgill** [comment]
Oh, right. Yes - ida-codacy-bot.

**Pull request merged**
